services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn course_platform_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: course_platform_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: course_db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: '1'

databases:
  - name: course_db
