services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate  # <-- This line runs your migration!
    startCommand: gunicorn course_platform_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: course_platform_backend.settings
      - key: DATABASE_URL
        value: postgresql://course_db_iz3s_user:4yF3UnGMFaeQZ9yeGTlAHeYyoscmqqfB@dpg-d037b9uuk2gs73eb79lg-a/course_db_iz3s
      - key: PYTHONUNBUFFERED
        value: '1'

databases:
  - name: course_db
