services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yourprojectname.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: course_platform.settings
      - key: DATABASE_URL
        fromDatabase:
          name: course_db
          property: connectionString

databases:
  - name: course_db
